# configuracion.yaml

model:
  save_model_directory: "./models" 
  input_dim: 213 # Número de características de entrada
  hidden_dim: 10 # Número de neuronas en la capa oculta
  num_layers: 3 # Número de capas ocultas
  output_dim: 1 # Una neurona para clasificación binaria (entre 0 y 1)

training:
  learning_rate: 0.001 # Tasa de aprendizaje
  batch_size: 64 # Tamaño del lote
  epochs: 10 # Número de épocas
  dropout_rate: 0.4 # Tasa de abandono
  prox_mu: 0.1 # Parámetro de proximidad
  strategy: "fedNova"  # Opciones: "fedAvg", "fedProx", "fedNova"

server:
  num_rounds: 20  # Número de rondas de entrenamiento
  server_address: "0.0.0.0:8080"  # Dirección del servidor


client:
  num_clients: 3  # Número de clientes
  train_data_path: "processed_data.csv"  # Ruta de los datos de entrenamiento