# configuracion.yaml

model:
  save_model_directory: "./models" 
  input_dim: 213 # Número de características de entrada
  hidden_dim: 5 # Número de neuronas en la capa oculta
  num_layers: 2 # Número de capas ocultas
  output_dim: 1 # Una neurona para clasificación binaria (entre 0 y 1)

training:
  learning_rate: 0.08 # Tasa de aprendizaje, para fedNova > 0.05, para el resto >= 0.0005
  batch_size: 64 # Tamaño del lote
  epochs: 3 # Número de épocas
  dropout_rate: 0.4 # Tasa de abandono
  prox_mu: 0.1 # Parámetro de proximidad
  local_steps: 5 # Número de pasos locales
  strategy: "scaffold"  # Opciones: "fedAvg", "fedProx", "fedNova", "custom", "scaffold"

server:
  num_rounds: 50  # Número de rondas de entrenamiento
  server_address: "0.0.0.0:8080"  # Dirección del servidor


client:
  num_clients: 10  # Número de clientes
  train_data_path: "diabetes_data.csv"  # Ruta de los datos de entrenamiento

# model:
#   save_model_directory: "./models" 
#   input_dim: 213 # Número de características de entrada
#   hidden_dim: 5 # Número de neuronas en la capa oculta
#   num_layers: 2 # Número de capas ocultas
#   output_dim: 1 # Una neurona para clasificación binaria (entre 0 y 1)

# training:
#   learning_rate: 0.1   # Tasa de aprendizaje
#   batch_size: 64 # Tamaño del lote
#   epochs: 3 # Número de épocas
#   dropout_rate: 0.4 # Tasa de abandono
#   prox_mu: 0.1 # Parámetro de proximidad
#   strategy: "fedNova"  # Opciones: "fedAvg", "fedProx", "fedNova", "custom"

# server:
#   num_rounds: 30  # Número de rondas de entrenamiento
#   server_address: "0.0.0.0:8080"  # Dirección del servidor


# client:
#   num_clients: 2  # Número de clientes
#   train_data_path: "diabetes_data.csv"  # Ruta de los datos de entrenamiento